### ISSUE TITLE
Statistics Rectagle Not Done.

### ISSUE THREAD

**Issue by MrMouse2405** [NorthernSantan/Rectangle-Program#2]
Statistics Rectangle is not done. 

You need to finish it.

Option 5 and 7 are needed to be done!

**Comment by colin-mccormack** [comment]
I am working on this issue right now and will close it once it is resolved.

**Comment by colin-mccormack** [comment]
Option 5 is now working.

**Comment by colin-mccormack** [comment]
**Solved** : Option 5 and Option 7 resolved. Option 5 required completely rewriting this function. Option 5 solution included fixing local operation functions, as well as adjusting pointer operations for the rectangle _stats_ object members. Option 7 was not making use of put or for each functions and then when it was it wasn't using the right parameters.
