### ISSUE TITLE
Quit Option Needs Update

### ISSUE THREAD

**Issue by MrMouse2405** [NorthernSantan/Rectangle-Program#3]
The quit option needs to do the following.

![image](https://user-images.githubusercontent.com/68935395/144968994-889a9328-16c2-4132-a950-22c6d8af349c.png)

We do need to print out the text into the file using the format from option 6.

Also, read me needs to be updated. FileWriter is NOT deprecated; its actual usage isn't implemented.

**Comment by MrMouse2405** [comment]
I'll do it myself. I am the expert of File Management and hardware related stuff lol.

**Comment by colin-mccormack** [comment]
Haha  @MrMouse2405 you are, I have some JSON formatting done in one handler function, but it might be better to just print them like the specified output currently. Possibility is to use sprintf based on printing function output.

**Comment by MrMouse2405** [comment]
Data will now be dumped into the Out/rectangles.json file. Information will be represented in a JSON format.
