### ISSUE TITLE
Option 7 Sorting

### ISSUE THREAD

**Issue by colin-mccormack** [NorthernSantan/Rectangle-Program#4]
Option 7 is sorting by insertion order instead of alphabetically by first rectangle name. 

![image](https://user-images.githubusercontent.com/80981213/145142157-8275435f-7c7f-4c59-84f8-625d9f7e1ddc.png)
![image](https://user-images.githubusercontent.com/80981213/145142172-a6b36918-26d2-4108-a1db-76dd0b0c9649.png)

This issue is _non-critical_ and should be resolved by submission date @MrMouse2405.

**Comment by colin-mccormack** [comment]
Solution specifications : Use sort in operations.c when printing

**Comment by MrMouse2405** [comment]
Need to add it to Statistics.

**Comment by colin-mccormack** [comment]
I will start on this issue right away.

**Comment by colin-mccormack** [comment]
The sort isn't working properly for me in clion, it always returns -1 (resulting in index 0) @MrMouse2405 .

![image](https://user-images.githubusercontent.com/80981213/145308365-8594b65f-de76-4815-a13d-80883cbc6177.png)

**Comment by colin-mccormack** [comment]
Sort solution created for rectangle and rectangle statistics.
